# =================================================================
# Clash Hysteria 1 (HY1) 纯 IPv4 专用节点订阅配置文件 (已禁用 IPv6)
# 自动化更新时间: 2026-09-29 22:51:33
# 纯 IPv4 HY1 节点总数: 4 个
# =================================================================
secret: github.com/Alvin9999-newpac/fanqiang
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: false

dns:
  enable: true
  ipv6: false
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32

proxies:
  - name: "HY1 节点 01 (62.210.70.191)"
    type: hysteria
    server: "62.210.70.191"
    port: 23556
    auth-str: "github.com/Alvin9999-newpac/fanqiang"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    alpn:
      - h3
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "HY1 节点 02 (62.210.70.191)"
    type: hysteria
    server: "62.210.70.191"
    port: 23556
    auth-str: "github.com/Alvin9999-newpac/fanqiang"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    alpn:
      - h3
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "HY1 节点 03 (5.83.129.90)"
    type: hysteria
    server: "5.83.129.90"
    port: 54177
    auth-str: "dongtaiwang.com"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    alpn:
      - h3
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"
  - name: "HY1 节点 04 (5.83.129.90)"
    type: hysteria
    server: "5.83.129.90"
    port: 54177
    auth-str: "dongtaiwang.com"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    alpn:
      - h3
    protocol: udp
    up: "11 Mbps"
    down: "55 Mbps"

proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - DIRECT
      - "HY1 节点 01 (62.210.70.191)"
      - "HY1 节点 02 (62.210.70.191)"
      - "HY1 节点 03 (5.83.129.90)"
      - "HY1 节点 04 (5.83.129.90)"
  - name: ♻️ 自动选择
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 5
    proxies:
      - "HY1 节点 01 (62.210.70.191)"
      - "HY1 节点 02 (62.210.70.191)"
      - "HY1 节点 03 (5.83.129.90)"
      - "HY1 节点 04 (5.83.129.90)"
  - name: 🌍 国外媒体
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - "HY1 节点 01 (62.210.70.191)"
      - "HY1 节点 02 (62.210.70.191)"
      - "HY1 节点 03 (5.83.129.90)"
      - "HY1 节点 04 (5.83.129.90)"
  - name: 📲 电报信息
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - "HY1 节点 01 (62.210.70.191)"
      - "HY1 节点 02 (62.210.70.191)"
      - "HY1 节点 03 (5.83.129.90)"
      - "HY1 节点 04 (5.83.129.90)"
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择
      - "HY1 节点 01 (62.210.70.191)"
      - "HY1 节点 02 (62.210.70.191)"
      - "HY1 节点 03 (5.83.129.90)"
      - "HY1 节点 04 (5.83.129.90)"
  - name: 🍎 苹果服务
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - "HY1 节点 01 (62.210.70.191)"
      - "HY1 节点 02 (62.210.70.191)"
      - "HY1 节点 03 (5.83.129.90)"
      - "HY1 节点 04 (5.83.129.90)"
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - ♻️ 自动选择
      - "HY1 节点 01 (62.210.70.191)"
      - "HY1 节点 02 (62.210.70.191)"
      - "HY1 节点 03 (5.83.129.90)"
      - "HY1 节点 04 (5.83.129.90)"
  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
      - "HY1 节点 01 (62.210.70.191)"
      - "HY1 节点 02 (62.210.70.191)"
      - "HY1 节点 03 (5.83.129.90)"
      - "HY1 节点 04 (5.83.129.90)"
  - name: 🍃 应用净化
    type: select
    proxies:
      - REJECT
      - DIRECT
      - "HY1 节点 01 (62.210.70.191)"
      - "HY1 节点 02 (62.210.70.191)"
      - "HY1 节点 03 (5.83.129.90)"
      - "HY1 节点 04 (5.83.129.90)"
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - ♻️ 自动选择
      - "HY1 节点 01 (62.210.70.191)"
      - "HY1 节点 02 (62.210.70.191)"
      - "HY1 节点 03 (5.83.129.90)"
      - "HY1 节点 04 (5.83.129.90)"

rules:
  - MATCH,🚀 节点选择
